name: Benchmarks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libtcc-dev

    - name: Build Compiler
      run: make ZC_HAS_JIT=1

    - name: Run Benchmarks
      run: ./tests/scripts/run_benchmarks.sh
